#!/usr/bin/env bash
# User installation. No development watchers; preserves pairing and configuration.
# Usage: PHONEPAD_PREBUILT=/path/phonepad bash setup/install.sh [--always-on]
set -euo pipefail
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_dir=$(cd -- "$script_dir/.." && pwd)
config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/phonepad
unit_dir=${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user
bin_dir=$HOME/.local/bin
ext_dst=$HOME/.local/share/gnome-shell/extensions/phonepad@local
always_on=false
if [[ ${1:-} == --always-on ]]; then always_on=true; elif [[ $# != 0 ]]; then echo 'Uso: install.sh [--always-on]' >&2; exit 1; fi
mkdir -p "$config_dir" "$unit_dir" "$bin_dir" "$ext_dst"
if [[ -n ${PHONEPAD_PREBUILT:-} ]]; then
 install -m 755 "$PHONEPAD_PREBUILT" "$bin_dir/phonepad.new"
else
 go_bin=$(command -v go || true)
 [[ -n $go_bin ]] || { echo 'Falta Go o PHONEPAD_PREBUILT.' >&2; exit 1; }
 (cd "$repo_dir/daemon"; "$go_bin" build -mod=vendor -o "$bin_dir/phonepad.new" .)
fi
mv "$bin_dir/phonepad.new" "$bin_dir/phonepad"
if [[ -f "$unit_dir/phonepad.service" ]]; then cp "$unit_dir/phonepad.service" "$unit_dir/phonepad.service.previous"; fi
install -m 644 "$script_dir/phonepad.service" "$unit_dir/phonepad.service"
install -m 644 "$script_dir/gnome-extension/phonepad@local/extension.js" "$ext_dst/extension.js"
install -m 644 "$script_dir/gnome-extension/phonepad@local/metadata.json" "$ext_dst/metadata.json"
# Existing configuration and identity are never regenerated by installation.
if [[ ! -f "$config_dir/service.env" ]]; then
 local_host=$(hostname)
 [[ $local_host =~ ^[A-Za-z0-9][A-Za-z0-9-]*$ ]] || { echo 'Hostname no compatible con mDNS.' >&2; exit 1; }
 umask 077
 printf 'PHONEPAD_BIND=127.0.0.1\nPHONEPAD_HOST=localhost\n' > "$config_dir/service.env"
fi
systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_RUNTIME_DIR 2>/dev/null || true
indicator_available=false
if /usr/bin/python3 -c "import gi; gi.require_version('AyatanaAppIndicator3', '0.1')" 2>/dev/null; then
 indicator_available=true
 mkdir -p "$HOME/.local/lib/phonepad"
 install -m 755 "$script_dir/indicator.py" "$HOME/.local/lib/phonepad/indicator.py"
 install -m 644 "$script_dir/phonepad-indicator.service" "$unit_dir/phonepad-indicator.service"
fi
if [[ -f "$config_dir/video.env" ]]; then
 mkdir -p "$HOME/.local/lib/phonepad"
 install -m 644 "$script_dir/preview/rtc.py" "$HOME/.local/lib/phonepad/rtc.py"
 for module in rate_control virtual_source process_backend hfr_worker hfr_runtime power_lease cursor_capture; do
  install -m 644 "$script_dir/preview/$module.py" "$HOME/.local/lib/phonepad/$module.py"
 done
 install -m 755 "$script_dir/preview/capture.py" "$HOME/.local/lib/phonepad/capture.py"
 install -m 644 "$script_dir/phonepad-preview.service" "$unit_dir/phonepad-preview.service"
fi
systemctl --user daemon-reload
if [[ -f "$config_dir/video.env" ]]; then systemctl --user enable phonepad-preview.service; systemctl --user restart phonepad-preview.service; fi
if $always_on; then systemctl --user enable phonepad.service; fi
systemctl --user restart phonepad.service
if $indicator_available; then
 systemctl --user enable phonepad-indicator.service
 systemctl --user restart phonepad-indicator.service
 # Keep a single Phonepad widget; avoid a duplicate on the next GNOME login.
 python3 - <<'PY'
import ast,subprocess
key=['org.gnome.shell','enabled-extensions']
raw=subprocess.check_output(['gsettings','get',*key],text=True).strip()
if raw.startswith('@as '): raw=raw[4:]
items=ast.literal_eval(raw)
if 'phonepad@local' in items:
 subprocess.run(['gsettings','set',*key,str([x for x in items if x!='phonepad@local'])],check=True)
PY
 echo 'Indicador Phonepad activo en la barra superior.'
elif gnome-extensions enable phonepad@local 2>/dev/null; then
 echo 'Botón Phonepad habilitado.'
else
 # Record requested state without replacing other enabled extensions.
 python3 - <<'PY'
import ast,subprocess
key=['org.gnome.shell','enabled-extensions']
raw=subprocess.check_output(['gsettings','get',*key],text=True).strip()
if raw.startswith('@as '): raw=raw[4:]
items=ast.literal_eval(raw)
if 'phonepad@local' not in items:
 items.append('phonepad@local')
 subprocess.run(['gsettings','set',*key,str(items)],check=True)
PY
 echo 'Botón instalado. GNOME Wayland puede requerir cerrar sesión y entrar una vez.'
fi
systemctl --user is-active phonepad.service
printf 'Emparejar una vez: https://localhost:8080/pair\nCompartir pantalla: https://localhost:8080/share\n'
